### ISSUE TITLE
Lista asignaturas/profesores

### ISSUE THREAD

**Issue by MiguelLillo** [GDUMA/Wikiuma#45]
- [ ]  Sugerir profesor
- [ ]  Sugerir asignatura

**Comment by Charly6596** [comment]
A qué te refieres con sugerir?

**Comment by Charly6596** [comment]
![image](https://user-images.githubusercontent.com/13708100/115989877-d3c2e080-a5c0-11eb-8558-913a102743c8.png)
![image](https://user-images.githubusercontent.com/13708100/115989882-d9b8c180-a5c0-11eb-9838-76f450d821c4.png)
